name: Build on TAG

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Flutter Build and Created Release and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #! Create a new release da tag
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}+${{ github.run_number }}

      #! Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get

      #! Build
      - run: flutter build apk --build-name=${{ github.ref_name }} --build-number=${{ github.run_number }}


      #! Get upload_url from release
      - name: Get release
        id: release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}


      #! Get name project
      - uses: bhowell2/github-substring-action@v1.0.0
        id: name_project
        with:
          value: ${{ github.repository }}
          index_of_str: /


      #! Upload the artifact for the release created
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ steps.name_project.outputs.substring }}_${{ github.ref_name }}+${{ github.run_number }}.apk
          asset_content_type: aplication/apk
